//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FabricIsvPlaybook.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FabricIsvPlaybook.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Copy Sales Data&quot;,
        ///  &quot;properties&quot;: {
        ///    &quot;activities&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;Copy_products&quot;,
        ///        &quot;type&quot;: &quot;Copy&quot;,
        ///        &quot;dependsOn&quot;: [],
        ///        &quot;policy&quot;: {
        ///          &quot;timeout&quot;: &quot;0.12:00:00&quot;,
        ///          &quot;retry&quot;: 0,
        ///          &quot;retryIntervalInSeconds&quot;: 30,
        ///          &quot;secureOutput&quot;: false,
        ///          &quot;secureInput&quot;: false
        ///        },
        ///        &quot;typeProperties&quot;: {
        ///          &quot;source&quot;: {
        ///            &quot;type&quot;: &quot;DelimitedTextSource&quot;,
        ///            &quot;storeSettings&quot;: {
        ///              &quot;type&quot;: &quot;AzureBlobFSRea [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CopySalesData_json {
            get {
                return ResourceManager.GetString("CopySalesData_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;nbformat&quot;: 4,
        ///  &quot;nbformat_minor&quot;: 5,
        ///  &quot;metadata&quot;: {
        ///    &quot;language_info&quot;: {
        ///      &quot;name&quot;: &quot;python&quot;
        ///    },
        ///    &quot;a365ComputeOptions&quot;: null,
        ///    &quot;sessionKeepAliveTimeout&quot;: 0,
        ///    &quot;trident&quot;: {
        ///      &quot;lakehouse&quot;: {
        ///        &quot;default_lakehouse&quot;: &quot;{LAKEHOUSE_ID}&quot;,
        ///        &quot;default_lakehouse_name&quot;: &quot;{LAKEHOUSE_NAME}&quot;,
        ///        &quot;default_lakehouse_workspace_id&quot;: &quot;{WORKSPACE_ID}&quot;,
        ///        &quot;known_lakehouses&quot;: [
        ///          {
        ///            &quot;id&quot;: &quot;{LAKEHOUSE_ID}&quot;
        ///          }
        ///        ]
        ///      }
        ///    }
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateLakehouseTables_ipynb {
            get {
                return ResourceManager.GetString("CreateLakehouseTables_ipynb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[create_all_tables]
        ///AS
        ///BEGIN
        ///
        ///  DROP TABLE IF EXISTS [dbo].[products];
        ///  CREATE TABLE [dbo].[products] (
        ///    [ProductId] [int] NULL,
        ///    [Product] [varchar](50) NULL,
        ///    [Category] [varchar](50) NULL
        ///  );
        ///
        ///  DROP TABLE IF EXISTS [dbo].[customers];
        ///  CREATE TABLE [dbo].[customers] (
        ///    [CustomerId] [int] NULL,
        ///    [Country] [varchar](50) NULL,
        ///    [City] [varchar](50) NULL,
        ///    [DOB] [date] NULL,
        ///    [Customer] [varchar](50) NULL,
        ///    [Age] [int] NULL
        ///  );
        ///
        ///  DRO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateSproc_CreateAllTables_sql {
            get {
                return ResourceManager.GetString("CreateSproc_CreateAllTables_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[refresh_calendar]
        ///AS
        ///BEGIN
        ///  -- create calendar table
        ///  SET datefirst 1;
        ///
        ///  DECLARE @MinDate date = (SELECT MIN([Date]) FROM sales)
        ///  DECLARE @MaxDate date =  (SELECT MAX([Date]) FROM sales)
        ///
        ///  DECLARE @StartDate date = (SELECT DATEFROMPARTS(YEAR(@MinDate), 1, 1))
        ///  DECLARE @EndDate date = (SELECT DATEFROMPARTS(YEAR(@MaxDate), 12, 31))
        ///
        ///  DECLARE @DayCount int = DATEDIFF(DAY, @StartDate, @EndDate) + 1
        ///
        ///  INSERT INTO calendar([Date], DateKey,  Year, Quarter, Month, Day,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateSproc_RefreshCalendar_sql {
            get {
                return ResourceManager.GetString("CreateSproc_RefreshCalendar_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[refresh_customers]
        ///AS
        ///BEGIN
        ///  INSERT INTO customers(CustomerId, Country, City, DOB, Customer, Age) 
        ///  SELECT 
        ///    CustomerId, 
        ///    Country, 
        ///    City, 
        ///    DOB,
        ///    Customer = CONCAT(FirstName, &apos; &apos;, LastName),
        ///    Age = YEAR(CURRENT_TIMESTAMP) - YEAR(DOB)
        ///  FROM staging.dbo.customers
        ///END.
        /// </summary>
        internal static string CreateSproc_RefreshCustomers_sql {
            get {
                return ResourceManager.GetString("CreateSproc_RefreshCustomers_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[refresh_products]
        ///AS
        ///BEGIN
        ///  INSERT INTO products(ProductId, Product, Category)
        ///  SELECT 
        ///    ProductId, 
        ///    Product, 
        ///    Category 
        ///  FROM staging.dbo.products
        ///END.
        /// </summary>
        internal static string CreateSproc_RefreshProducts_sql {
            get {
                return ResourceManager.GetString("CreateSproc_RefreshProducts_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[refresh_sales]
        ///AS
        ///BEGIN
        ///
        ///  INSERT INTO sales([Date], DateKey, CustomerId, ProductId, Quantity, Sales) 
        ///  SELECT 
        ///    [Date], 
        ///    DateKey = (YEAR([Date]) * 10000) + (MONTH([Date]) * 100) + DAY([Date]),
        ///    CustomerId,
        ///    ProductId, 
        ///    Quantity, 
        ///    Sales = SalesAmount
        ///  FROM staging.dbo.invoices 
        ///  INNER JOIN staging.dbo.invoice_details 
        ///  ON staging.dbo.invoices.InvoiceId = staging.dbo.invoice_details.InvoiceId
        ///
        ///END.
        /// </summary>
        internal static string CreateSproc_RefreshSales_sql {
            get {
                return ResourceManager.GetString("CreateSproc_RefreshSales_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;nbformat&quot;: 4,
        ///  &quot;nbformat_minor&quot;: 5,
        ///  &quot;metadata&quot;: {
        ///    &quot;language_info&quot;: {
        ///      &quot;name&quot;: &quot;python&quot;
        ///    },
        ///    &quot;a365ComputeOptions&quot;: null,
        ///    &quot;sessionKeepAliveTimeout&quot;: 0,
        ///    &quot;trident&quot;: {
        ///      &quot;lakehouse&quot;: {
        ///        &quot;default_lakehouse&quot;: &quot;{LAKEHOUSE_ID}&quot;,
        ///        &quot;default_lakehouse_name&quot;: &quot;{LAKEHOUSE_NAME}&quot;,
        ///        &quot;default_lakehouse_workspace_id&quot;: &quot;{WORKSPACE_ID}&quot;,
        ///        &quot;known_lakehouses&quot;: [
        ///          {
        ///            &quot;id&quot;: &quot;{LAKEHOUSE_ID}&quot;
        ///          }
        ///        ]
        ///      }
        ///    }
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateStagingLakehouse_ipynb {
            get {
                return ResourceManager.GetString("CreateStagingLakehouse_ipynb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Data pipeline - Create Stored Procedures for Warehouse&quot;,
        ///  &quot;objectId&quot;: &quot;14f253ce-fd6a-4c74-808d-e430d10fed07&quot;,
        ///  &quot;properties&quot;: {
        ///    &quot;activities&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;Create refresh_products&quot;,
        ///        &quot;type&quot;: &quot;Script&quot;,
        ///        &quot;dependsOn&quot;: [],
        ///        &quot;policy&quot;: {
        ///          &quot;timeout&quot;: &quot;0.12:00:00&quot;,
        ///          &quot;retry&quot;: 0,
        ///          &quot;retryIntervalInSeconds&quot;: 30,
        ///          &quot;secureOutput&quot;: false,
        ///          &quot;secureInput&quot;: false
        ///        },
        ///        &quot;linkedService&quot;: {
        ///          &quot;n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateStoredProcedures_json {
            get {
                return ResourceManager.GetString("CreateStoredProcedures_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TABLE IF EXISTS [dbo].[products];
        ///CREATE TABLE [dbo].[products] (
        ///  [ProductId] [int] NULL,
        ///  [Product] [varchar](50) NULL,
        ///  [Category] [varchar](50) NULL
        ///);
        ///
        ///DROP TABLE IF EXISTS [dbo].[customers];
        ///CREATE TABLE [dbo].[customers] (
        ///  [CustomerId] [int] NULL,
        ///  [Country] [varchar](50) NULL,
        ///  [City] [varchar](50) NULL,
        ///  [DOB] [date] NULL,
        ///  [Customer] [varchar](50) NULL,
        ///  [Age] [int] NULL
        ///);
        ///
        ///DROP TABLE IF EXISTS [dbo].[sales];
        ///CREATE TABLE [dbo].[sales] (
        ///  [Date] [date] NULL,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateTables_sql {
            get {
                return ResourceManager.GetString("CreateTables_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROCEDURE [dbo].[create_all_tables]
        ///AS
        ///BEGIN
        ///
        ///  DROP TABLE IF EXISTS [dbo].[products];
        ///  CREATE TABLE [dbo].[products] (
        ///    [ProductId] [int] NULL,
        ///    [Product] [varchar](50) NULL,
        ///    [Category] [varchar](50) NULL
        ///  );
        ///
        ///  DROP TABLE IF EXISTS [dbo].[customers];
        ///  CREATE TABLE [dbo].[customers] (
        ///    [CustomerId] [int] NULL,
        ///    [Country] [varchar](50) NULL,
        ///    [City] [varchar](50) NULL,
        ///    [DOB] [date] NULL,
        ///    [Customer] [varchar](50) NULL,
        ///    [Age] [int] NULL
        ///  );
        ///
        ///  DRO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateWarehouseSprocs_sql {
            get {
                return ResourceManager.GetString("CreateWarehouseSprocs_sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Create Warehouse Tables&quot;,
        ///  &quot;objectId&quot;: &quot;712f51d0-ab01-4fc1-ada8-b527dfd43110&quot;,
        ///  &quot;properties&quot;: {
        ///    &quot;activities&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;Create Warehouse Tables&quot;,
        ///        &quot;type&quot;: &quot;Script&quot;,
        ///        &quot;dependsOn&quot;: [],
        ///        &quot;policy&quot;: {
        ///          &quot;timeout&quot;: &quot;0.12:00:00&quot;,
        ///          &quot;retry&quot;: 0,
        ///          &quot;retryIntervalInSeconds&quot;: 30,
        ///          &quot;secureOutput&quot;: false,
        ///          &quot;secureInput&quot;: false
        ///        },
        ///        &quot;linkedService&quot;: {
        ///          &quot;name&quot;: &quot;sales&quot;,
        ///          &quot;obje [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateWarehouseTables_json {
            get {
                return ResourceManager.GetString("CreateWarehouseTables_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;CY24SU02&quot;,
        ///  &quot;dataColors&quot;: [
        ///    &quot;#118DFF&quot;,
        ///    &quot;#12239E&quot;,
        ///    &quot;#E66C37&quot;,
        ///    &quot;#6B007B&quot;,
        ///    &quot;#E044A7&quot;,
        ///    &quot;#744EC2&quot;,
        ///    &quot;#D9B300&quot;,
        ///    &quot;#D64550&quot;,
        ///    &quot;#197278&quot;,
        ///    &quot;#1AAB40&quot;,
        ///    &quot;#15C6F4&quot;,
        ///    &quot;#4092FF&quot;,
        ///    &quot;#FFA058&quot;,
        ///    &quot;#BE5DC9&quot;,
        ///    &quot;#F472D0&quot;,
        ///    &quot;#B5A1FF&quot;,
        ///    &quot;#C4A200&quot;,
        ///    &quot;#FF8080&quot;,
        ///    &quot;#00DBBC&quot;,
        ///    &quot;#5BD667&quot;,
        ///    &quot;#0091D5&quot;,
        ///    &quot;#4668C5&quot;,
        ///    &quot;#FF6300&quot;,
        ///    &quot;#99008A&quot;,
        ///    &quot;#EC008C&quot;,
        ///    &quot;#533285&quot;,
        ///    &quot;#99700A&quot;,
        ///    &quot;#FF4141&quot;,
        ///    &quot;#1F9A85&quot;,
        ///    &quot;#25891C&quot;,
        ///    &quot;#0057A2&quot;,
        ///    &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CY24SU02_json {
            get {
                return ResourceManager.GetString("CY24SU02_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0&quot;,
        ///  &quot;datasetReference&quot;: {
        ///    &quot;byPath&quot;: null,
        ///    &quot;byConnection&quot;: {
        ///      &quot;connectionString&quot;: null,
        ///      &quot;pbiServiceModelId&quot;: null,
        ///      &quot;pbiModelVirtualServerName&quot;: &quot;sobe_wowvirtualserver&quot;,
        ///      &quot;pbiModelDatabaseName&quot;: &quot;{SEMANTIC_MODEL_ID}&quot;,
        ///      &quot;name&quot;: &quot;EntityDataSource&quot;,
        ///      &quot;connectionType&quot;: &quot;pbiServiceXmlaStyleLive&quot;
        ///    }
        ///  }
        ///}
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string definition_pbir {
            get {
                return ResourceManager.GetString("definition_pbir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;version&quot;: &quot;1.0&quot;,
        ///  &quot;settings&quot;: {}
        ///}
        ///
        ///
        ///
        ///.
        /// </summary>
        internal static string definition_pbism {
            get {
                return ResourceManager.GetString("definition_pbism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;NewExecutive&quot;,
        ///  &quot;dataColors&quot;: [
        ///    &quot;#3257A8&quot;,
        ///    &quot;#37A794&quot;,
        ///    &quot;#8B3D88&quot;,
        ///    &quot;#DD6B7F&quot;,
        ///    &quot;#6B91C9&quot;,
        ///    &quot;#F5C869&quot;,
        ///    &quot;#77C4A8&quot;,
        ///    &quot;#DEA6CF&quot;,
        ///    &quot;#597CF4&quot;,
        ///    &quot;#4AC5BB&quot;,
        ///    &quot;#BA4AC5&quot;,
        ///    &quot;#C54A53&quot;,
        ///    &quot;#4A53C5&quot;,
        ///    &quot;#FEE266&quot;,
        ///    &quot;#3E9B80&quot;,
        ///    &quot;#C54A91&quot;,
        ///    &quot;#2545B5&quot;,
        ///    &quot;#05A595&quot;,
        ///    &quot;#801689&quot;,
        ///    &quot;#89161E&quot;,
        ///    &quot;#161F89&quot;,
        ///    &quot;#BDA750&quot;,
        ///    &quot;#047257&quot;,
        ///    &quot;#891658&quot;,
        ///    &quot;#182D79&quot;,
        ///    &quot;#0F5C55&quot;,
        ///    &quot;#540F5C&quot;,
        ///    &quot;#5C0F15&quot;,
        ///    &quot;#0F155C&quot;,
        ///    &quot;#7E6F36&quot;,
        ///    &quot;#074B3F&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NewExecutive_json {
            get {
                return ResourceManager.GetString("NewExecutive_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;name&quot;: &quot;Refresh All Tables&quot;,
        ///  &quot;objectId&quot;: &quot;6aa9f93a-3256-4712-ad7c-ea1f7e514455&quot;,
        ///  &quot;properties&quot;: {
        ///    &quot;activities&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;Execute refresh_products&quot;,
        ///        &quot;type&quot;: &quot;SqlServerStoredProcedure&quot;,
        ///        &quot;dependsOn&quot;: [],
        ///        &quot;policy&quot;: {
        ///          &quot;timeout&quot;: &quot;0.12:00:00&quot;,
        ///          &quot;retry&quot;: 0,
        ///          &quot;retryIntervalInSeconds&quot;: 30,
        ///          &quot;secureOutput&quot;: false,
        ///          &quot;secureInput&quot;: false
        ///        },
        ///        &quot;typeProperties&quot;: {
        ///          &quot;storedProcedureNa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RefreshAllTables_json {
            get {
                return ResourceManager.GetString("RefreshAllTables_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;compatibilityLevel&quot;: 1604,
        ///  &quot;model&quot;: {
        ///    &quot;annotations&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;__PBI_TimeIntelligenceEnabled&quot;,
        ///        &quot;value&quot;: &quot;1&quot;
        ///      }
        ///    ],
        ///    &quot;collation&quot;: &quot;Latin1_General_100_BIN2_UTF8&quot;,
        ///    &quot;culture&quot;: &quot;en-US&quot;,
        ///    &quot;cultures&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;en-US&quot;,
        ///        &quot;linguisticMetadata&quot;: {
        ///          &quot;content&quot;: {
        ///            &quot;DynamicImprovement&quot;: &quot;HighConfidence&quot;,
        ///            &quot;Language&quot;: &quot;en-US&quot;,
        ///            &quot;Version&quot;: &quot;1.0.0&quot;
        ///          },
        ///          &quot;contentType&quot;: &quot;json&quot;
        ///        }
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sales_model_DirectLake_bim {
            get {
                return ResourceManager.GetString("sales_model_DirectLake_bim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;compatibilityLevel&quot;: 1567,
        ///  &quot;model&quot;: {
        ///    &quot;annotations&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;__PBI_TimeIntelligenceEnabled&quot;,
        ///        &quot;value&quot;: &quot;0&quot;
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;PBIDesktopVersion&quot;,
        ///        &quot;value&quot;: &quot;2.122.746.0 (23.10)&quot;
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;PBI_QueryOrder&quot;,
        ///        &quot;value&quot;: &quot;[\&quot;Products\&quot;,\&quot;CSV_FILE_ROOT\&quot;,\&quot;Customers\&quot;,\&quot;Sales\&quot;,\&quot;Invoices\&quot;]&quot;
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;PBI_ProTooling&quot;,
        ///        &quot;value&quot;: &quot;[\&quot;DevMode\&quot;]&quot;
        ///      }
        ///    ],
        ///    &quot;culture&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sales_model_import_bim {
            get {
                return ResourceManager.GetString("sales_model_import_bim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;compatibilityLevel&quot;: 1567,
        ///  &quot;model&quot;: {
        ///    &quot;annotations&quot;: [
        ///      {
        ///        &quot;name&quot;: &quot;__PBI_TimeIntelligenceEnabled&quot;,
        ///        &quot;value&quot;: &quot;0&quot;
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;PBIDesktopVersion&quot;,
        ///        &quot;value&quot;: &quot;2.126.1261.0 (24.02)&quot;
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;PBI_ProTooling&quot;,
        ///        &quot;value&quot;: &quot;[\&quot;DevMode\&quot;]&quot;
        ///      },
        ///      {
        ///        &quot;name&quot;: &quot;PBI_QueryOrder&quot;,
        ///        &quot;value&quot;: &quot;[\&quot;Products\&quot;,\&quot;CSV_FILE_ROOT\&quot;,\&quot;Customers\&quot;,\&quot;Sales\&quot;,\&quot;Invoices\&quot;]&quot;
        ///      },
        ///      {
        ///        &quot;nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sales_model_import_v2_bim {
            get {
                return ResourceManager.GetString("sales_model_import_v2_bim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;config&quot;: &quot;{\&quot;version\&quot;:\&quot;5.51\&quot;,\&quot;themeCollection\&quot;:{\&quot;baseTheme\&quot;:{\&quot;name\&quot;:\&quot;CY24SU02\&quot;,\&quot;version\&quot;:\&quot;5.51\&quot;,\&quot;type\&quot;:2}},\&quot;activeSectionIndex\&quot;:0,\&quot;bookmarks\&quot;:[{\&quot;displayName\&quot;:\&quot;GoToSalesSummary\&quot;,\&quot;name\&quot;:\&quot;Bookmark6f5e36cc8e2f3a092c1a\&quot;,\&quot;explorationState\&quot;:{\&quot;version\&quot;:\&quot;1.3\&quot;,\&quot;activeSection\&quot;:\&quot;ReportSection\&quot;,\&quot;filters\&quot;:{\&quot;byExpr\&quot;:[{\&quot;name\&quot;:\&quot;Filterc78765fc0917a6c3c326\&quot;,\&quot;type\&quot;:\&quot;Categorical\&quot;,\&quot;filter\&quot;:{\&quot;Version\&quot;:2,\&quot;From\&quot;:[{\&quot;Name\&quot;:\&quot;l\&quot;,\&quot;Entity\&quot;:\&quot;Languages\&quot;,\&quot;Type\&quot;:0}],\&quot;W [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sales_report_json {
            get {
                return ResourceManager.GetString("sales_report_json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;config&quot;: &quot;{\&quot;version\&quot;:\&quot;5.51\&quot;,\&quot;themeCollection\&quot;:{\&quot;baseTheme\&quot;:{\&quot;name\&quot;:\&quot;CY24SU02\&quot;,\&quot;version\&quot;:\&quot;5.51\&quot;,\&quot;type\&quot;:2},\&quot;customTheme\&quot;:{\&quot;name\&quot;:\&quot;NewExecutive\&quot;,\&quot;version\&quot;:\&quot;5.51\&quot;,\&quot;type\&quot;:2}},\&quot;activeSectionIndex\&quot;:0,\&quot;bookmarks\&quot;:[{\&quot;displayName\&quot;:\&quot;GoToSalesSummary\&quot;,\&quot;name\&quot;:\&quot;Bookmark6f5e36cc8e2f3a092c1a\&quot;,\&quot;explorationState\&quot;:{\&quot;version\&quot;:\&quot;1.3\&quot;,\&quot;activeSection\&quot;:\&quot;ReportSection\&quot;,\&quot;filters\&quot;:{\&quot;byExpr\&quot;:[{\&quot;name\&quot;:\&quot;Filterc78765fc0917a6c3c326\&quot;,\&quot;type\&quot;:\&quot;Categorical\&quot;,\&quot;filter\&quot;:{\&quot;Ver [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sales_report_v2_json {
            get {
                return ResourceManager.GetString("sales_report_v2_json", resourceCulture);
            }
        }
    }
}
